services:
  backend:
    build: .              # Image creation
    ports:
      - "8000:8000"                                    
    env_file:
      - .env
    environment:
      DB_URL: postgresql://postgres:password@db:5432/ai_document  
    depends_on:
      - db  

  db:
    build: ./postgres        # Image creating : if u wanna download image then use image: IMG_NAME
    environment:
      POSTGRES_DB: ai_document
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - ./postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  